# Generated by Django 4.2.6 on 2023-10-30 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JSONData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='json_files/')),
                ('data', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
