# Generated by Django 4.2.6 on 2024-04-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('json_handler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsondata',
            name='author',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='jsondata',
            name='upload_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
